apiVersion: apps/v1
kind: Deployment
metadata:
  name: swoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swoom
  template:
    metadata:
      labels:
        app: swoom
    spec:
      containers:
      - name: swoom
        image: ghostgeneral14/swoom
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
